name = "catalog"

[targets.default]
url = "s3://${FDL_S3_BUCKET}"
public_url = "https://data.queria.io"
s3_endpoint = "${FDL_S3_ENDPOINT}"
s3_access_key_id = "${FDL_S3_ACCESS_KEY_ID}"
s3_secret_access_key = "${FDL_S3_SECRET_ACCESS_KEY}"

[meta]
title = "Queriaカタログ"
description = "Queriaで公開している全データセット・テーブルのメタデータ"
tags = ['カタログ', 'Queria']
repository_url = "https://github.com/flo8s/dataset-catalog"

[meta.schemas]
main.title = "メイン"
