catalog:
  target: default
  outputs:
    default:
      type: duckdb
      path: "md:?motherduck_token={{ env_var('MOTHERDUCK_TOKEN', '') }}"
      database: catalog
      schema: main
      threads: 4
      extensions:
        - httpfs
        - motherduck
        - ducklake
      attach:
        - path: "md:catalog"
          alias: catalog
          is_ducklake: true
    local:
      type: duckdb
      path: "md:?motherduck_token={{ env_var('MOTHERDUCK_TOKEN', '') }}"
      database: catalog
      schema: main
      threads: 4
      extensions:
        - httpfs
        - motherduck
        - ducklake
      attach:
        - path: "md:dev_catalog"
          alias: catalog
          is_ducklake: true
